# Generated by Django 3.0.3 on 2020-10-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201008_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='desc',
            field=models.CharField(default='cat', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=50),
        ),
    ]
